packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": latest
  "@types/node": latest
  "@types/react": latest
  "@types/react-dom": latest
  "@typescript-eslint/eslint-plugin": latest
  "@typescript-eslint/parser": latest
  "eslint": latest
  "fastify": latest
  "expo": latest
  "expo-router": latest
  "dotenv": latest
  "@fastify/cors": latest
  "@types/pg": latest
  "kysely": latest
  "next": latest
  "next-auth": latest
  "pg": latest
  "react-native": latest
  "react": latest
  "react-dom": latest
  "vite": latest
  "tsx": latest
  "turbo": latest
  "typescript": 5.9.3
  "vitest": latest
  "zod": latest
